### ISSUE TITLE
Jest doesn't recognize snarkyjs 

### ISSUE THREAD

**Issue by Trivo25** [o1-labs/snapp-cli#126]
Running tests that include snarkyjs imports (eg `Field`) fails, more precisely, jest crashes with the following error message:

https://pastebin.com/LpHXr5gn

Note the long mysterious error produced by snarkyjs before the actual error

```
    SyntaxError: Unexpected token 'export'
    > 1 | import { Field } from 'snarkyjs';
```

This error *only* occures when functions are being tested that use snarkyjs imports, eg `Field`, like the example below

```ts
import { Field } from 'snarkyjs';

export function foo(): number {
  let f = Field(0); // this causes jest to crash
  return 1;
}

```

the following example works fine

```ts
import { Field } from 'snarkyjs';

export function foo(): number {
  // I removed the Field(0) constructor here!
  return 1;
}

```

Steps to re produce:

Using the snapp cli to create a new project with `snapp project new_project`

Write a test that tests the following function 

```ts

// index.ts
import { Field } from 'snarkyjs';

export function foo(): number {
  let f = Field(0); // this causes jest to crash
  return 1;
}


// index.test.ts
import { foo } from './index';

describe('index.ts', () => {
  describe('foo()', () => {
    it('should be correct', () => {
      expect(foo()).toEqual(1);
    });
  });
});

```

run `yarn test`

Using mocha to test the exact same files work
see the mocha config used in a working example here https://github.com/Trivo25/mina-zk-rollup/blob/main/.mocharc.json

**Comment by MartinMinkov** [comment]
Hey Trivo!

What is the current version of the `snapp-cli` you are running? I suspect that you are pulling an old version and not getting all the files that are needed to run the Jest tests. There should be a `resolver.cjs` file in your repo after running `snapp project new_project`, can you confirm this is the case?

**Comment by Trivo25** [comment]
> Hey Trivo!
> 
> What is the current version of the `snapp-cli` you are running? I suspect that you are pulling an old version and not getting all the files that are needed to run the Jest tests. There should be a `resolver.cjs` file in your repo after running `snapp project new_project`, can you confirm this is the case?

Hey Martin, thanks for the fast reply. I did in fact not have a `resolver.cjs`. I double-checked my `snapp-cli` version (`0.1.30`) and re-installed the cli and created a new project again, just to be sure - I still don't have `resolver.cjs`


`snapp system` output

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 16.13.1 - /usr/local/node-v16.13.1-linux-x64/bin/node
    Yarn: 1.22.15 - /usr/local/node-v16.13.1-linux-x64/bin/yarn
    npm: 8.1.2 - /usr/local/node-v16.13.1-linux-x64/bin/npm
  npmPackages:
    snarkyjs: ^0.1.9 => 0.1.9 
  npmGlobalPackages:
    snapp-cli: 0.1.30
```

same issue persists on my windows machine - is 0.1.30 perhaps not the correct version? I double checked the package.json of this repo, it seems to be the correct version

**Comment by MartinMinkov** [comment]
I suspect this is a problem with how files are being fetched from Github and then being cached on the system. 

There should be a `.gittar/` directory in your home directory. If there is, could you remove that and then try reusing the snapp-cli?

**Comment by Trivo25** [comment]
Awesome, deleting `.gittar` fixed it. Thank you very much for your help :)
