### ISSUE TITLE
Cloing project templates sometimes fails with an unhelpful error message

### ISSUE THREAD

**Issue by dillongrove** [o1-labs/snapp-cli#31]
System: M1 MacBook Air

Running the create project command gives me:
```
% snap proj myproj
x Clone project template
could not find commit hash for main
ERROR: MISSING_REF
```

Some research indicates that this likely a problem with `degit` which is used to fetch project templates:
https://github.com/Rich-Harris/degit/issues/37

Note that `git` _is_ installed and available on PATH on this machine. Per the suggestion in the issue linked above, setting `cache: false` in degit options does seem to fix this issue in a pinch. However, that might not be a good long-term solution.

Others suggest that the XCode Command Line Utilities might need to be installed on Mac for this work. This machine actually _does not_ have those installed, so I will try that soon and see if it works with `cache: true`. If so, we could make this part of the installation instructions.

Alternatively, we could look into other methods of fetching project templates ([gittar](https://github.com/lukeed/gittar) is one that apparently has similar functionality but doesn't depend on git).

**Comment by dillongrove** [comment]
Per conversation on 7/26/2021:
Try setting `force: true`, deleting cache, and trying again

**Comment by jasongitmail** [comment]
Also, try clearing contents of `~/.degit` and running `npm install` in the `snapp-cli` dir again. Then trying the command that caused the error. 

iirc, `force:true` might get past this too, but we won't be able to ship with this setting b/c overwrites the destination dir's contents, if the dir already exists. Although, we could add a manual check to confirm the dir doesn't exist before invoking degit, to get around it. TLDR if `force:true` gets around it, it's probably an upstream issue in degit.

**Comment by jasongitmail** [comment]
I ended up using `gittar` to implement the example command b/c using two degit's calls felt like it'd get messy with its event emitter syntax. 

It works well. I'm down to use gittar to work around this issue. Its syntax will end up slightly cleaner & looks like we'll be able to set it up for offline usage.

**Comment by jasongitmail** [comment]
Fixed. Switched to gittar.
