### ISSUE TITLE
Add helper method to create a Tx that can create or update a Snapp account

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snapp-cli#37]
`src/helpers`. Or is this just a function call to the ClientSDK?

It would consume the verification key generated by the CLI's `build` command & user's private key and return a Tx. The Tx would be ready to send to a Tx relayer, but don't worry about sending it anywhere.

**Comment by MartinMinkov** [comment]
Quick questions regarding the implementation of this:
1. Do we know what the format of a SNAPP transaction is? I just wanted to check if there was some existing format we should follow or if this is purely a mock.
2. What does the returned output of the CLI's `build` command look like? Any other data included outside the verification key?
3. Maybe out of scope for now, but would we want to do any sort of validation of the private key before transaction creation?

**Comment by jasongitmail** [comment]
Good questions. Let's chat

**Comment by jasongitmail** [comment]
Closing b/c we decided this will live in the Mina JavaScript Client SDK.
