### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jasongitmail** [o1-labs/snapp-cli#41]
- [x] 1. Git warns about line endings Mac vs Windows when committing. Can fix via [.gitattributes](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings). Fixed in [commit](https://github.com/o1-labs/snapp-cli/commit/64516ffad65d12e432c5b2b62e702bd717b64a59).
- [ ] 2. When user types `snapp project myproj`, we update `package.json` with this name. This works on Mac & Linux. But on windows, it appears like this `c:\path\to\myproj` for an unknown reason.
- [ ] 3. `npm install` causes an error of `system cannot find the path specified` for an unknown reason.

**Comment by jasongitmail** [comment]
@dillongrove is working on this

**Comment by MartinMinkov** [comment]
Closed with https://github.com/o1-labs/snapp-cli/pull/68
